### ISSUE TITLE
Quotes in conversation titles are displayed incorrectly on the browser tab

### ISSUE THREAD

**Issue by freshlycutgrass** [geteso/eso#10]
On the browser tab label, double quotes (") placed in a conversation title display as \&quot; and single quotes display as \&#39;
Backslashes also seem to display as \&#92;
This also seems to occur in blockquotes, if a user has quotes or apostrophies in their name.

**Comment by aokod** [comment]
> I believe this is caused by the way the forum sanitizes user input.

It is definitely possible to "over-sanitize" user input and that seems to be the case with the browser tabs. I'll have to see what went wrong.
