### ISSUE TITLE
Eso Roadmap

### ISSUE THREAD

**Issue by andromeda-Z** [geteso/eso#20]
Bugs to fix:
The default avatar is flipped to the left instead of alternating when a new post is sent in a conversation
Lack of recent PHP support due to outdated MySQL functions
Needed missing hooks in controllers

Features to add:
Ability to hide certain tags from the normal search
Post attachments
More BBCode tags, like font size and colour
iFrame embeds, for YouTube and plenty of other sites
A better captcha, such as ReCaptcha
A way to ignore a user and block their posts and conversations
An avatar cropping system
More avatar format support, such as WebP, SVG, BMP etc
Profile customisation features, such as a bio and banner images
Notifications system, with desktop notifications and a bell to show all the notifications that you have received. Along with this there should be reports for posts and accounts, and possibly a post verification system, where the first few posts must be approved by an administrator before your account can freely post
Accessibility features, such as dark mode skins and colorblind skins.

**Comment by andromidaZ** [comment]
Additionally, a public software testing forum would be helpful for newcomers to the software

**Comment by GigaHacer** [comment]
What do you mean by needed missing hooks in controllers? It's very easy to place hooks wherever needed so I would think that's an easy fix. Just make a pull request adding all the hooks which you think are necessary.

**Comment by andromeda-Z** [comment]
> What do you mean by needed missing hooks in controllers? It's very easy to place hooks wherever needed so I would think that's an easy fix. Just make a pull request adding all the hooks which you think are necessary.

Ok. Will do.

**Comment by aokod** [comment]
Many of these features/bugs have now been added/fixed or are already present in the software.  I will go down the line and address each of them.

1. The default avatar thumb (the small avatar for mobile devices) now alternates between members in the conversation view.
2. PHP 8.0 has been tested and should now be supported as of commit 44105ba.  The MySQLi (improved) driver has been supported as of commit ad016b4.
3. This was addressed by @GigaHacer but "add more hooks" should not really be on the roadmap unless there is a need for a particular hook to be added so a plugin can function properly.
4. This is already possible by adding an exclamation mark before a tag (e.g. !tag:tutorial will exclude conversations with that tag) or before some gambits, also known as a reverse operator.

Some of the things you mentioned, such as embedding YouTube videos, should be very easy to accomplish with a plugin.  Remember that esoBB is meant to be lightweight (as barebones as possible while also remaining functional) and extensible.
