### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by andromeda-Z** [geteso/eso#21]
On the header of each file included in the software there is a copyright notice 
>Copyright (C) 2022 geteso.org.  <https://geteso.org>

However such copyright does not exist at all, or I cannot find it in any public records. Having a false copyright notice breaks US Law and can lead to a fine of up to $2,500.

> Any person who, with fraudulent intent, places on any article a notice of copyright or words of the same purport that such person knows to be false, or who, with fraudulent intent, publicly distributes or imports for public distribution any article bearing such notice or words that such person knows to be false, shall be fined not more than $2,500. [17 USC § 506(c)](http://www.copyright.gov/title17/92chap5.html#506).

**Comment by aokod** [comment]
https://www.copyright.gov/help/faq/faq-general.html
