### ISSUE TITLE
Bug with formatting in conversations

### ISSUE THREAD

**Issue by Beta-51** [geteso/eso#6]
If you are to put everything included here to "\\" and post it, it'll error out, but still send the post. However, it'll end up as a draft, but everyone can see it. You cannot post in it, and it's overall just a buggy mess when you interact with it. doesn't seem to work on the official geteso website.
![image](https://user-images.githubusercontent.com/65312404/146709537-75563114-a83a-40a9-ae00-99d03edb0ecd.png)

**Comment by Beta-51** [comment]
I do think i know why this happens, it's probably because \\" makes the " become a ignored quote thing. you could make \\ become \\\\, and so on.

**Comment by GigaHacer** [comment]
This issue isn't present in the current iteration of the software. I tried making a conversation with the title, tags and content being \ and there were no issues. I believe this bug no longer exists.

**Comment by aokod** [comment]
@Beta-51 mentioned that this issue isn't present on geteso.org either.  I would be interested to know about their operating system / PHP / SQL server version so I can diagnose this further.

**Comment by aokod** [comment]
oops - didn't mean to do that!
