### ISSUE TITLE
Broken tab in the Dashboard

### ISSUE THREAD

**Issue by freshlycutgrass** [geteso/eso#9]
There's a tab called "Member-Plural" which has one checkbox and the formatting is messed up

**Comment by aokod** [comment]
Seems to be a bug with how language strings are translated in the dashboard.

**Comment by GigaHacer** [comment]
> Seems to be a bug with how language strings are translated in the dashboard.

It's because the dashboard tabs weren't written as language strings.

**Comment by aokod** [comment]
See #11 - closed!
